#!/bin/sh

# Image files from FLIR camera have additional data embedded.
# This script extracts some.

if [ "x$1" = "x--" ]; then
    shift
fi

extractEmbedded()
{
    what="$1"
    src="$2"
    dst="$3"
    exiftool -b -"$what" "$src" > "$dst" && touch -r "$src" "$dst"
}

while [ $# -gt 0 ]; do
    src="$1"
    basename="${1%.*}"
    shift

    echo "$basename"
    extractEmbedded EmbeddedImage   "$src" "${basename}.photo.jpg"
    extractEmbedded RawThermalImage "$src" "${basename}.rawthermal"
    extractEmbedded Palette         "$src" "${basename}.palette"
done
