#!/usr/bin/env python3

import sys
import os


def main():
    line_numbers = {}
    idx = 1
    with open(os.path.expanduser('~/.bash_history'), 'rb') as f:
        for raw_line in f.readlines():
            line = raw_line.strip()
            line_numbers[line] = idx
            idx += 1

    line_numbers = sorted(line_numbers.items(), key=lambda x: x[1])
    sys.stdout.buffer.write(b'\n'.join([x[0] for x in line_numbers]))
    sys.stdout.buffer.write(b'\n')


if __name__ == '__main__':
    main()
