#!/bin/sh

if [ "x$1" = "x" ]; then
    echo "$0: missing image 1" >&2
    exit 2
fi

if [ "x$2" = "x" ]; then
    echo "$0: missing image 2" >&2
    exit 2
fi

convert "$1" "$2" -compose difference -composite PPM:- | feh -
