#!/bin/bash

check_tool() {
    if ! command -v "$1" >/dev/null; then
        echo >&2 "ERROR: can't find tool: $1$2"
        exit 2
    fi
}

check_tool vid2webm
check_tool file

if [ "x$1" = "x--" ]; then
    shift
fi

while (($#)); do
    FILETYPE=$(file -b --mime-type "$1")

    if [[ "x$FILETYPE" == "ximage/gif" ]]; then
        mkdir -p done || true
        vid2webm "$1" "${1%.*}.gifv" && mv -i "$1" "${1%.*}.gifv" done/
        shift; continue
    fi

    if [[ "x$FILETYPE" == "xvideo/webm" ]]; then
        mkdir -p done || true
        vid2webm "$1" "${1%.*}.gifv" && mv -i "$1" "${1%.*}.gifv" done/
        shift; continue
    fi

    echo >&2 "skipped: $1"
    shift
done
