#!/usr/bin/env python3

# find list entries which are not downloaded yet

import sys
import os

with open(sys.argv[1]) as f:
    links = [x.strip() for x in f.readlines()]

for link in links:
    fname = os.path.basename(link)
    try:
        with open(fname) as f:
            pass
    except IOError:
        print(link)
