#!/bin/bash

if [ "x$1" = "x--" ]; then
    shift
fi

while (($#)); do
    framecount=$(ffprobe -v error -select_streams v:0 -count_packets -show_entries stream=nb_read_packets -of csv=p=0 -- "$1" | tr -d ',')
    printf "%6s  %s\n" "$framecount" "$1"
    shift
done
